version: "3.8"
services:
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: encuentros_db
    environment:
      ORACLE_PASSWORD: admin
      ORACLE_DATABASE: XEPDB1
      APP_USER: ENCUENTROS_ADMIN
      APP_USER_PASSWORD: admin
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-db:/container-entrypoint-initdb.d
    restart: always

  backend:
    build:
      context: ./encuentros-back
    container_name: encuentros_back
    environment:
      DB_HOST: db
      DB_PORT: "1521"
      DB_USERNAME: ENCUENTROS_ADMIN
      DB_PASSWORD: admin
      DB_SERVICE_NAME: XEPDB1
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./encuentros-front
    container_name: encuentros_front
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  oracle_data:
